version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:30"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    groups:
      go-modules:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:45"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
